### ISSUE TITLE
Wrong symbol for second sunken ship

### ISSUE THREAD

**Issue by Chloshette** [Djidiouf/bship#4]
When the ennemy sunk my second ship the symbol stayed a O instead of a Q
See underneath, the E1 ship

![2015-07-18 19_05_44-c__windows_system32_cmd exe - python main py](https://cloud.githubusercontent.com/assets/13391456/8761052/5ee4094c-2d80-11e5-973e-a8f49213bc0c.png)

**Comment by Djidiouf** [comment]
Thank you for your feedback. the issue has been solved in the last develop branch. It will be soon incorporated in the master one.
